"""
Explanation Agent — rewrites the compliance report in plain professional language.

Input:  full AgentState (compliance report + freshness verdicts)
Output: final_response with human-readable findings and disclaimer
"""

from __future__ import annotations

import time
from typing import Any, Dict, List

import structlog
from langchain_core.messages import HumanMessage, SystemMessage

from src.agents.llm import get_llm
from src.agents.state import AgentState, AgentStep, FinalResponse

log = structlog.get_logger(__name__)

DISCLAIMER_RU = (
    "⚠️ Данный анализ выполнен с помощью искусственного интеллекта на основе нормативной базы. "
    "Результаты носят информационный характер. Верифицируйте выводы с лицензированным инженером "
    "или проектировщиком перед подачей проектной документации в уполномоченные органы."
)

DISCLAIMER_EN = (
    "⚠️ This analysis was generated by AI based on the regulatory knowledge base. "
    "Results are informational only. Verify all findings with a licensed engineer "
    "or architect before submitting project documentation to authorities."
)

SYSTEM_PROMPT = """Вы — опытный технический консультант по строительным нормам Казахстана.

Ваша задача: переписать технический отчёт о соответствии нормам в понятный, профессиональный язык для архитекторов и инженеров.

Правила:
1. Сохраняйте все ссылки на источники (номера документов и статей)
2. Объясняйте технические требования простыми словами
3. Чётко выделяйте нарушения и необходимые действия
4. Добавляйте практические советы по устранению нарушений
5. Отвечайте на том же языке, на котором задан вопрос
6. НЕ добавляйте информацию, которой нет в предоставленном отчёте"""


def _detect_language(state: AgentState) -> str:
    """Detect query language from building parameters or notes."""
    notes = state.get("notes", "") + state.get("purpose", "")
    # Simple heuristic: presence of Cyrillic suggests Russian/Kazakh
    import re
    cyrillic = len(re.findall(r"[а-яёА-ЯЁ]", notes))
    return "ru" if cyrillic > 3 else "en"


def _build_user_prompt(state: AgentState, language: str) -> str:
    report = state.get("compliance_report") or {}
    items = report.get("items", [])
    verdicts = state.get("freshness_verdicts", {})
    mcp_ok = state.get("mcp_available", False)

    # Build findings text
    findings_text = []
    for item in items:
        doc = item.get("doc_name", "")
        freshness = verdicts.get(doc, {})
        freshness_str = freshness.get("verdict", "UNVERIFIED") if mcp_ok else "UNVERIFIED"
        findings_text.append(
            f"- [{item.get('status')}] {item.get('article_ref')}: "
            f"{item.get('description')} "
            f"(актуальность нормы: {freshness_str})"
        )

    overall_risk = report.get("overall_risk", "UNKNOWN")
    violations = report.get("violations", 0)
    actions = report.get("requires_action", 0)

    if language == "ru":
        prompt = f"""Параметры объекта: {state.get('building_type')} {state.get('floors')} этажей, {state.get('city')}, {state.get('material')}, {state.get('purpose')}

Технический отчёт о соответствии:
Общий уровень риска: {overall_risk}
Нарушений: {violations} | Требуют действий: {actions}

Находки:
{chr(10).join(findings_text)}

Перепишите этот отчёт в профессиональном, понятном стиле. Укажите конкретные действия для устранения нарушений."""
    else:
        prompt = f"""Building parameters: {state.get('building_type')} {state.get('floors')} floors, {state.get('city')}, {state.get('material')}, {state.get('purpose')}

Compliance analysis report:
Overall risk: {overall_risk}
Violations: {violations} | Requires action: {actions}

Findings:
{chr(10).join(findings_text)}

Rewrite this report in clear, professional language. Include specific actions to address violations."""

    return prompt


def explanation_agent(state: AgentState) -> Dict[str, Any]:
    """
    LangGraph node: Explanation Agent.

    Rewrites the compliance report in plain language and assembles
    the final user-facing response with disclaimer.
    """
    start = time.monotonic()
    log.info("explanation_agent_start", session_id=state.get("session_id"))

    try:
        language = _detect_language(state)
        disclaimer = DISCLAIMER_RU if language == "ru" else DISCLAIMER_EN

        report = state.get("compliance_report")
        if not report or not report.get("items"):
            # No compliance data — return a graceful "not found" message
            final: FinalResponse = {
                "summary": (
                    "Нормативные документы для данного типа объекта не найдены в базе данных. "
                    "Попробуйте уточнить параметры запроса."
                    if language == "ru"
                    else "No regulatory documents found for this building type. Please refine your query."
                ),
                "findings": [],
                "disclaimer": disclaimer,
                "language": language,
            }
            step: AgentStep = {
                "agent": "ExplanationAgent",
                "status": "done",
                "message": "No compliance data — returned empty response",
                "duration_ms": 0,
            }
            return {
                "final_response": final,
                "explanation_error": None,
                "agent_trace": state.get("agent_trace", []) + [step],
            }

        llm = get_llm()

        # --- RAG-only fallback (no LLM configured) ---
        if llm is None:
            verdicts = state.get("freshness_verdicts", {})
            mcp_ok = state.get("mcp_available", False)
            findings: List[Dict] = []
            for item in report.get("items", []):
                doc = item.get("doc_name", "")
                freshness_data = verdicts.get(doc, {"verdict": "UNVERIFIED", "source_url": ""})
                findings.append({
                    "article_ref": item.get("article_ref", ""),
                    "doc_name": doc,
                    "status": item.get("status", "ADVISORY"),
                    "description": item.get("description", ""),
                    "plain_language": item.get("plain_language", item.get("description", "")),
                    "risk_level": item.get("risk_level", "ADVISORY"),
                    "freshness": {
                        "verdict": freshness_data.get("verdict", "UNVERIFIED"),
                        "source_url": freshness_data.get("source_url", ""),
                        "mcp_verified": mcp_ok,
                    },
                })
            if language == "ru":
                plain_summary = (
                    f"Найдено {len(findings)} соответствующих нормативных документов. "
                    "Ниже приведены выдержки из релевантных норм и правил. "
                    "Для полного анализа на соответствие настройте LLM (OpenAI или Ollama)."
                )
            else:
                plain_summary = (
                    f"Found {len(findings)} relevant regulatory document(s). "
                    "The excerpts below are from matching norms. "
                    "For full AI compliance analysis, configure an LLM (OpenAI or Ollama)."
                )
            final: FinalResponse = {
                "summary": plain_summary,
                "findings": findings,
                "disclaimer": disclaimer,
                "language": language,
            }
            duration_ms = int((time.monotonic() - start) * 1000)
            step: AgentStep = {
                "agent": "ExplanationAgent",
                "status": "done",
                "message": f"RAG-only mode — {len(findings)} document excerpts returned",
                "duration_ms": duration_ms,
            }
            return {
                "final_response": final,
                "explanation_error": None,
                "agent_trace": state.get("agent_trace", []) + [step],
            }
        # --- End RAG-only fallback ---

        messages = [
            SystemMessage(content=SYSTEM_PROMPT),
            HumanMessage(content=_build_user_prompt(state, language)),
        ]
        response = llm.invoke(messages)
        plain_summary = response.content.strip()

        # Build structured findings list for the frontend
        verdicts = state.get("freshness_verdicts", {})
        mcp_ok = state.get("mcp_available", False)
        findings: List[Dict] = []
        for item in report.get("items", []):
            doc = item.get("doc_name", "")
            freshness_data = verdicts.get(doc, {"verdict": "UNVERIFIED", "source_url": ""})
            findings.append({
                "article_ref": item.get("article_ref", ""),
                "doc_name": doc,
                "status": item.get("status", "ADVISORY"),
                "description": item.get("description", ""),
                "plain_language": item.get("plain_language", ""),
                "risk_level": item.get("risk_level", "LOW"),
                "freshness": {
                    "verdict": freshness_data.get("verdict", "UNVERIFIED"),
                    "source_url": freshness_data.get("source_url", ""),
                    "mcp_verified": mcp_ok,
                },
            })

        final: FinalResponse = {
            "summary": plain_summary,
            "findings": findings,
            "disclaimer": disclaimer,
            "language": language,
        }

        duration_ms = int((time.monotonic() - start) * 1000)
        step: AgentStep = {
            "agent": "ExplanationAgent",
            "status": "done",
            "message": f"Generated plain-language report with {len(findings)} findings",
            "duration_ms": duration_ms,
        }

        log.info("explanation_agent_done", findings=len(findings), duration_ms=duration_ms)

        return {
            "final_response": final,
            "explanation_error": None,
            "agent_trace": state.get("agent_trace", []) + [step],
        }

    except Exception as exc:
        duration_ms = int((time.monotonic() - start) * 1000)
        log.exception("explanation_agent_error", error=str(exc))
        step: AgentStep = {
            "agent": "ExplanationAgent",
            "status": "error",
            "message": str(exc),
            "duration_ms": duration_ms,
        }
        return {
            "final_response": None,
            "explanation_error": str(exc),
            "agent_trace": state.get("agent_trace", []) + [step],
            "errors": state.get("errors", []) + [f"ExplanationAgent: {exc}"],
        }
